[stats]
drivability = 35.0
sportiness = 35.0
reliability = 65.0
safety = 36.0
practicality = 40.0
comfort = 20.0
cost = 35000
fuel_economy = 7.8			# Liters / 100 km

[rules]
or = [
	["drivability", "sportiness"],
	["practicality", "comfort"]
]

[engine]
max_year = 2003
#max_cylinders = 4			# This works too but I'm showcasing the ASS regulations lol
turbo_max_cylinders = 4
octane = 91					# In RON
max_total_valves = 4

[wheels]
must_match = true
front_max_width = 205
front_max_profile = 50
front_max_rim = 16
banned_compounds = ["Semi-Slick"]

[other]
# required_parts = [
# 	"test",					# Require part called "test"
# 	["opt1", "opt2"]		# Require either "opt1" or "opt2"
# ]
banned_parts = []			# Does not support `or` like required_parts, same otherwise
