[stats]
drivability = 27.0
safety = 27.0
comfort = 15.0
cost = 55000
fuel_economy = 7.8			# Liters / 100 km

[chassis]
banned_materials = ["Carbon Fibre"]

[engine]
min_year = 2018
max_year = 2018
max_cylinders = 6
max_displacement = 1600
octane = 98
fuel_type = ["Unleaded"]
max_total_valves = 4
catalytic_converter_banned = ["High Flow"]
intake_banned = ["Race", "Variable"]
headers_banned = ["Turbo Race"]

[wheels]
front_min_width = 125
front_max_width = 200
front_wheel_diameter = 650
rear_min_width = 125
rear_max_width = 200
rear_wheel_diameter = 650
banned_rim_materials = ["Carbon Fibre"]

[drivetrain]
banned_types = ["4x4"]

[other]
required_parts = [
	["Baffled", "Reverse Flow"]
]
min_quality = -5
max_quality = 3
