[stats]
drivability = 35.0
sportiness = 35.0
reliability = 65.0
safety = 36.0
practicality = 40.0
comfort = 20.0

[rules]
or = [["drivability", "sportiness"], ["practicality", "comfort"]]

[engine]
max_year = 2003
#max_cylinders = 4 # This works too but I'm showcasing the ASS regulations lol
turbo_max_cylinders = 4
