# WRC!!!
[stats]
sportiness = 40.0
offroad = 30.0
safety = 45.0
cost = 150000
fuel_economy = 11.5

[rules]
or = [["offroad", "sportiness"]]

[chassis]
banned_materials = ["Carbon Fibre"]

[engine]
min_year = 2018
max_year = 2018
max_cylinders = 6
max_displacement = 1600
octane = 98
fuel_type = ["Unleaded"]
catalytic_converter_banned = ["High Flow"]
intake_banned = ["Race", "Variable"]
headers_banned = ["Turbo Race"]

[wheels]
front_min_width = 125
front_max_width = 205
front_wheel_diameter = 650
front_max_rim = 18
rear_min_width = 125
rear_max_width = 205
rear_wheel_diameter = 650
rear_max_rim = 18
banned_rim_materials = ["Carbon Fibre"]

[drivetrain]
banned_types = ["4x4"]

[other]
required_parts = [
    ["Baffled", "Reverse Flow"],
    "Radial",
    "All-Terrain",
    ["Manual", "Automanual"]
]
banned_parts = [
    "Variable Hydraulic",
    "Electric Variable",
    "Viscious LSD",
    "Electric LSD"
]
min_quality = -5
max_quality = 5
